apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMjCCAhqgAwIBAgIIDlCOArr1N4MwDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
    HhcNMjUxMTAxMTUxOTI0WhcNMzUxMDMwMTUxOTI0WjA3MRIwEAYDVQQLEwlvcGVu
    c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBANwcK3nT8/G9jiCMGNQbdNjODxHU2x7x
    SVUg3ankvfyCwF9kz1EZ+ZOSoC7P9ZrRKU4mlBmEDlX90ekUNuBmzFDPKdzQFkcN
    RqZ+E/aAgK8TKzvZqTYBnhJcJTjn9c+1LfV+h1SMSx4kCOC9YnZb+Zg72QS8QfVp
    Y6RP4KFV+wv2T19L1q+dIBA6yqHwFz8TUK6rNvuG++hAtZMnmC4aSseUgCeuCc80
    LTifAmYHv9ZLCkYXFWxpCtJxqbhj3mexSnTKTTSUHTrIAG2YvYGi6mv1ddZ8sBVr
    voqzd/D9tSo3Q8zEn4akdYpMHIy9tuzogZA2Y/+qJff0acPTIteuf8sCAwEAAaNC
    MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCz/
    PukoEQEw9x8XruPPUGe011uXMA0GCSqGSIb3DQEBCwUAA4IBAQDIh6ikiV3OHjNc
    JCxLjpmtGjDIMrbYcik4NnpSW9V6EAPsn5hLcifYG+BcWSCXCRtDCtGIZBGmq7M9
    8xMkz65kkXfwAxJsTFpTrJ5rM8/vm+fA/9Rx/QbBwKqzjmj4BWA6Y2rUFrnIaw7H
    T6Y2W0HWBlxkxr8s9o4RfyiNwI5CXVOQNbu5/W1/CU9TyAVhDYLuGLhQkfDqdnAu
    O4/ufWMB5bOzMVrSDvkaDZzrz0HkrVTr5VAgJFgAMknWZJI+Y4tf/PlDQBSexAKp
    XNb39AJcYMt9DDLFBlbWB9u5vL74a+nfsHDOjJ/qo3WCRMijFCFLCDHx7dKY8VQW
    C9khPYEZ
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIIby9MYFkegfQwDQYJKoZIhvcNAQELBQAwPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMB4XDTI1MTEwMTE1MTkyNFoXDTM1MTAzMDE1MTkyNFowPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArztvESHN8mqx
    wa+hHA/0k4xvOzQy4YOcfHbfHpX6sMi1D9tiCD/bAut4wPgH4DBqwGcrfyPLkyS1
    gygren6hH62lXoWrpREWl+lJjyZJpy3QTqL1YiNJfC1HOniI2Zx9ttIHsdqUiTUU
    wKC0Dd0ECZTQoeAOMh4A9TCD9RlwMbZ7sGpCLYSjDrOJxDXoQYegddPQn/Sf60Wk
    Lvej01f2C5Ge+laer4zy3W2+AjA3xvVmwZBeCEb1z3naC1GcSkxXAmQWCjf9UGPK
    gJgOXvX81hsuoYhRtPp+uTxudHvoQkhZhEAurFXiYKEm2eAchNxuYTtHDydfW+eF
    KyGvyPrtqQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUe4sfOKurFlJUIY16j6lKLQTjY8swDQYJKoZIhvcNAQELBQAD
    ggEBAIcG4O5+cI9fiM0jsrE3J11FzWdPsvMPvVdtVJgF2J3PIiPnS1d+G+CjDUKv
    m40eSMxb6aB3Oby6RUTBRPRY7jPla1niwljD4Rp4N2VsSFgY8T4MnXZDkxQnEKk9
    gWP/+s4lSfxgjxnQ7jHSEsIR+BVxTfywJ/WhBFsssTw61K3Ys7lQBxFejK39TcPI
    hW+xYN8pEJ4mku6K3mU0hC0SUxeMwYmpMLDyERTezvMrRP88QPEpgU19woEIA/NN
    BTqLL+/Nz/Iiw6M2egdXs/GZx/OBjUP5Voiid1HiMggytxrS9KATAuD+h8FvWkhu
    gKxMLAVcKVtg70YvAIRlOpeQNCY=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIICVELfdIy23wwDQYJKoZIhvcNAQELBQAwRDESMBAGA1UE
    CxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2aWNlLW5l
    dHdvcmstc2lnbmVyMB4XDTI1MTEwMTE1MTkyNFoXDTM1MTAzMDE1MTkyNFowRDES
    MBAGA1UECxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2
    aWNlLW5ldHdvcmstc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAr543FgwIC5gKTbtH0hkHTBYKul6nk4knGrEfcsxMbSM9ms/WlUgwLYWRKV0D
    ho6S/T32Qz6xS8KEKJPUgb2zLbe8cDhZH82e2VVGnaXNcRZFEkK21zYLzLooozs/
    zQtZZLNqs1abi6nLocCPbahauysTensg+orzdx3NGjCX/BFDwGomJk/FV1P0QbIx
    JDgAit96L9BTesp9Gzj7z5BMAIDR5/9cPigYI2vq2royFqIL8dbJtf3aLKKgkGg4
    Di1X8ZhClMclGjFJkK7oMb433+HdI/bHttxOYJJULhDrfObyVmokD56gsKg15qSs
    6sgUke2rcS6iMI1seTY45/qJRwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUGHrmdC85sAAGrRIm+cQj60uwtvowDQYJ
    KoZIhvcNAQELBQADggEBACxYKwKhSFOQ2OTbhGz4VsBDmQj6jQoNtXqhiHEEWo40
    jBUH62mrSp9aThkP3AMSLTQILnO3Bqatu01Ur3LpKAQUxBLXPYAttQXTK5tSL0Ak
    MOB+xTigrlTeCp1QctUosTrl44eJduZhZcCts3Btw9DWPHFPapGDU/tCc/q6OnOt
    V+PovLcAl6iX6LVg0UXyDFpnQPiulrU5ladLyfokYJQGN9BrMd1g7sDPmgESmbwr
    mpmOJqd6+vBSRhrFa9cekjqGasXqMb+QyFADataXKSAMl/3LWZZsGh1qHAl65x7j
    Z+kpXSzVWNjK66LMamJPfhFmvt9PkhT1GcCFN00uhe8=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDlzCCAn+gAwIBAgIIK5wkaGamS+kwDQYJKoZIhvcNAQELBQAwWTFXMFUGA1UE
    AwxOb3BlbnNoaWZ0LWt1YmUtYXBpc2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1y
    ZWNvdmVyeS1zZXJ2aW5nLXNpZ25lckAxNzYyMDE0MTY0MB4XDTI1MTEwMTE2MjI0
    M1oXDTM1MTAzMDE2MjI0NFowWTFXMFUGA1UEAwxOb3BlbnNoaWZ0LWt1YmUtYXBp
    c2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1yZWNvdmVyeS1zZXJ2aW5nLXNpZ25l
    ckAxNzYyMDE0MTY0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3U3e
    l2Ca413CIvCVT2pjgL+R5mxk2zSTg9CxHVHKCiFkeqN1gaae3NecHw2zNgYTIAJm
    azvA/N9LybOkh/ww98hIke1xewzukVRPThXvey7tSeBx0NIQy6ml2MmZjJAiP1PU
    D5dgLwaPHGU84hdnolkdPabtsjkhEyQDryA/mzEBna9yATEqx713F13s1XUm92r5
    ZsICHQGGKeW36tLapwFVFCZkXaZTpqZCf23ovVvUbCtVJiGAefRveAcSiRNDOuWg
    xkk+O1a5zCuVwP/kK6Ldd3ewgQ/12lrq6U2j0qj+RvWmyX5dBdTpoXZ/JIFkji2I
    EMOzYE3x8HqfgowTJQIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQUvfmbVcmoVjQnAmhVWydr9kleve8wHwYDVR0jBBgw
    FoAUvfmbVcmoVjQnAmhVWydr9kleve8wDQYJKoZIhvcNAQELBQADggEBABO6uFIx
    cHH2vnc+5VdgIUagRR+0R3Edf9qYOsCkQotTdH0AfKliAW9RPL0n6D1rE5Zwi50B
    m+fBxysBkr4rGteuxl1Busgxp7Ti9UoYwGKFFYmbb1TrW06fmwHrfwttrAJFzSRg
    cvHqQ/YgeO9XwWF/oM1DmtDQ4S5ibv/Ds4fmztT5J7dnaTkG0NjuhTMg49YELWlC
    HX1dDqpfG2ITXFQ2gTCnRVg39JV+006K5OOW2YnIleEYDp+0Mjq+jdXpSLHsv7cF
    z85E0AOnrZpgfUy8zKfRUDkncK27oEl6+Fo1x2RMaX4v1QBG4fnRdbKOfJfR3+zS
    jls4FKDDVAj3XGE=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDaTCCAlGgAwIBAgIIZGJ6SnDgOHkwDQYJKoZIhvcNAQELBQAwJjEkMCIGA1UE
    AwwbaW5ncmVzcy1vcGVyYXRvckAxNzYyMDE0MjA0MB4XDTI1MTEwMTE2MjMyNFoX
    DTI3MTEwMTE2MjMyNVowJDEiMCAGA1UEAwwZKi5hcHBzLmlyb25tYW4uY2psYWJz
    LmRldjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALu8iY9oJhB9dJn7
    3fNlBADdsX3e53Blo9WZRwKcGfsgNXrJfddBKLQ9DvV8+yIGNJYHxYYMg2DE/3C/
    qr2b+QxpYe8Q1E5L505ADyZw36gEw0kJiSkpTtvRdA9c9WqdVAG7zHe5vcsxhDKW
    I5EGsfzlpeX0v3u79NG/DnnSgyGweexbB0wnLDKG/3m0RgIhXPx7k/zPY06QXGxT
    U2cRDapUr++BeeBb6vNt2IazSNt7N+hFmVA0t+EPfMf867MZsrpy7PLbwda+xvD/
    Mpn4Lqa3lnIx7wZDryRFRxFpxc5aKbVqSnafds5+9TnjQCG2s/m3Azio3/dslrek
    tTdi4xsCAwEAAaOBnDCBmTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYB
    BQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUZ7Lfi1ECpRNSNrQ0ToVlNNlO
    BvowHwYDVR0jBBgwFoAU66fAovaWzWZzsifnGms2B+nyz6EwJAYDVR0RBB0wG4IZ
    Ki5hcHBzLmlyb25tYW4uY2psYWJzLmRldjANBgkqhkiG9w0BAQsFAAOCAQEAYUlK
    cLnhrheho3p2EOsG6lMlJ5Dju4EZG9XeaStEDxHGMO30SP3RSLfWKXzFfm1oxBoE
    384saJ7V9/ePwEq5nzARfbi86GJutM+NA0jh13F901GfFyynob/D/e6bSpiafhGu
    XdxI1gaXQgAxxpj2HwLYldKWU8AvOxXiu6QM5/JhVLKIJEk3ctnrnYRramTQJ1DU
    XBrnvgN8+nc65D79Kf2q/ihbdzg0YfJdDXfwzdQ3XpwFWgJt4it97Ep8iFuB7kVk
    Ead+0hIY6eE08/lpksRAxoKAKU8aevwyE+cW0NSxcvHkxCqq05Tw1VdoKbeNbfU/
    vwGE+Bg3tjQLSjNpXQ==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtpbmdy
    ZXNzLW9wZXJhdG9yQDE3NjIwMTQyMDQwHhcNMjUxMTAxMTYyMzIzWhcNMjcxMTAx
    MTYyMzI0WjAmMSQwIgYDVQQDDBtpbmdyZXNzLW9wZXJhdG9yQDE3NjIwMTQyMDQw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC+OmNdS4ktS0y3mNp28ZSt
    BpF5Tf8THBIsIufha6X3xx0CyOFX24j7eR9n+q++hUwppgwD+2xXLTfw+E846ZS9
    nfcgcFQfMzHpRhaekXdmqByQwxk6DkL2gBSEfJ0thU6rEwcJBW3JEDL8xzhl+Xp5
    ny7p+O8B9/FDnJ2quJ5xZ+/iV2rCUOzbd8iLDYWY2kVhTMGxU3UfQW8yp70fE1F3
    alLTu3XeH/LAUaOddZoDoXQdysgas7AKA/dEsw5swzayL/2hQMbb/C2y+RemxVgm
    Pk/OHgF0O5pM2fIfpo9SaMgoBK+YkWWJpdWLyzwZvnTeKz/+pz8eU1xUytL+jIuJ
    AgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdDgQWBBTrp8Ci9pbNZnOyJ+caazYH6fLPoTANBgkqhkiG9w0BAQsFAAOCAQEA
    kZib3hk0C3hbtvsu+yEVCOJS0rfKTtHQOFAyKLM5mPbw6/kVfb4Cs7wJS8H0HjlD
    ru8nO2oFFuoiN6kLbztCNJySHEIjo/Fu9zeQqojJsLplN5CjtKF/LzEQ7DG64EQw
    Ssx8osIK/EDZg1YULmfTJPYCA0oD6MyQw+n5fhp3/+6SU3U8rhCJOE7pG0FJ8PIe
    2yPi/OUbr24LidTfeuV5Si/tX44DlCtT1yKDwGJVj/mG8OWGwVO4TPmhrKjG63wv
    OYOkk5eq6MPFlPsUBuDsQRlz3HLgGniB0qMcWVOJ904GAqBNMKo7UtEYLOAbztJT
    qAH/xew3o4LppykQl28jfQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  name: kube-root-ca.crt
  namespace: n8n
